In [29]:
from sklearn.datasets import load_digits
digit = load_digits()
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
import numpy as np
import matplotlib.pyplot as plt

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(digit.data,digit.target,test_size = 0.3)

In [13]:
lr = LogisticRegression(solver = 'liblinear',multi_class= 'ovr',)
lr.fit(X_train,Y_train)
lr.score(X_test,Y_test)

0.9574074074074074

In [24]:
svm = SVC(gamma = 'auto')
svm.fit(X_train,Y_train)
svm.score(X_test,Y_test)

0.5925925925925926

In [15]:
rf = RandomForestClassifier(n_estimators= 40)
rf.fit(X_train,Y_train)
rf.score(X_test,Y_test)

0.9740740740740741

#K fold cross validation(basic example)

In [16]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3,)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [18]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index,test_index)



[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


# cross_val_score function

In [19]:
from sklearn.model_selection import cross_val_score

# Logistic regression model performance using cross_val_score

In [21]:
cross_val_score(LogisticRegression(solver = 'liblinear',multi_class='ovr'),digit.data,digit.target,cv= 3)

array([0.89482471, 0.95325543, 0.90984975])

# svm model performance using cross_val_score

In [25]:
cross_val_score(SVC(gamma = 'auto'),digit.data,digit.target,cv= 3)

array([0.38063439, 0.41068447, 0.51252087])

#random forest performance using cross_val_score

In [26]:
cross_val_score(RandomForestClassifier(n_estimators=40),digit.data,digit.target,cv= 3)

array([0.93155259, 0.94991653, 0.94490818])

#  cross_val_score uses stratifield kfold by default

# Parameter tunning using k fold cross validation

In [32]:
score1 = cross_val_score(RandomForestClassifier(n_estimators=5),digit.data,digit.target,cv= 10)
np.average(score1)

0.8803724394785848

In [33]:
score2 = cross_val_score(RandomForestClassifier(n_estimators=10),digit.data,digit.target,cv= 10)
np.average(score2)

0.9143016759776537

In [34]:
score3 = cross_val_score(RandomForestClassifier(n_estimators=20),digit.data,digit.target,cv= 10)
np.average(score3)

0.9354438237119801

In [35]:
score4 = cross_val_score(RandomForestClassifier(n_estimators=50),digit.data,digit.target,cv= 10)
np.average(score4)

0.9515890751086282

In [40]:
score5 = cross_val_score(RandomForestClassifier(n_estimators=40),digit.data,digit.target,cv= 10)
np.average(score5)

0.9443265052762259

### Here we used cross_val_score to fine tune our random forest classifier and figured that having around 50 trees in random forest gives best result.