In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df1 = pd.read_csv("E:\Machine_Learning\\data.csv")
df1

Area  Bedrooms  Age   Price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [3]:
X=df1.Bedrooms.median()
X

4.0

In [4]:
df1.Bedrooms = df1.Bedrooms.fillna(X)
df1

Area  Bedrooms  Age   Price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
df_new = df1.drop('Price',axis = 1)
df_new

Area  Bedrooms  Age
0  2600       3.0   20
1  3000       4.0   15
2  3200       4.0   18
3  3600       3.0   30
4  4000       5.0    8
5  4100       6.0    8

In [6]:
reg = linear_model.LinearRegression()
reg.fit(df_new, df1.Price)


LinearRegression()

In [7]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [8]:
reg.intercept_

221323.00186540408

In [9]:
reg.predict([[3000,3,40]])

C:\Users\USER\sample_project_1\env\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [10]:
reg.predict([[2500,4,5]])

C:\Users\USER\sample_project_1\env\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

# Exercise

In [11]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n

In [12]:
df = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/Exercise/hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [13]:
df.experience = df.experience.fillna('zero')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [14]:
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [15]:
import math

In [16]:
k = math.floor(df['test_score(out of 10)'].mean())
k

7

In [18]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(k)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [19]:
test_score = df['test_score(out of 10)'].median()
test_score

7.5

In [30]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(test_score)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [21]:
new_df=df.drop('salary($)',axis = 1)
new_df

experience  test_score(out of 10)  interview_score(out of 10)
0           0                    8.0                           9
1           0                    8.0                           6
2           5                    6.0                           7
3           2                   10.0                          10
4           7                    9.0                           6
5           3                    7.0                          10
6          10                    7.0                           7
7          11                    7.0                           8

In [22]:
salary =df['salary($)']
salary

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64

In [23]:
model1 = linear_model.LinearRegression()
model1.fit(new_df,df['salary($)'])

LinearRegression()

In [36]:
model1.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])#we can use this syntex also

LinearRegression()

In [24]:
model1.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [25]:
model1.intercept_

14992.65144669314

In [26]:
model1.predict([[2,9,6]])

C:\Users\USER\sample_project_1\env\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [27]:
model1.predict([[12,10,10]])

C:\Users\USER\sample_project_1\env\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])

# Saving Model using Pickle and Joblib

In [37]:
import pickle

In [48]:
with open('model_pickle','wb') as file:
         pickle.dump(model1,file)

In [49]:
with open('model_pickle','rb') as fil:
    mp = pickle.load(fil)

In [50]:
mp.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [51]:
mp.intercept_

14992.65144669314

In [53]:
mp.predict([[2,9,6]])

C:\Users\USER\sample_project_1\env\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [54]:
mp.predict([[12,10,10]])

C:\Users\USER\sample_project_1\env\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])

In [57]:
import sklearn.externals
import joblib

In [58]:
joblib.dump(model1,'model_joblib')

['model_joblib']

In [60]:
mj=joblib.load('model_joblib')
mj

LinearRegression()

In [61]:
mj.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [62]:
mj.intercept_

14992.65144669314

In [63]:
mj.predict([[2,9,6]])

C:\Users\USER\sample_project_1\env\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [65]:
mj.predict([[12,10,10]])

C:\Users\USER\sample_project_1\env\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])