In [1]:
import numpy as np
a=np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [2]:
np.max(a)#return max value

50

In [3]:
np.min(a)#return min value

10

In [4]:
np.argmin(a)#return index of min value

0

In [7]:
np.argmax(a)#return index of max value

4

In [8]:
np.sqrt(a)#return square root of every value

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [9]:
np.sin(a)#return sin of every value

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [11]:
np.cos(a)#return cos of every value

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603])

In [13]:
import numpy as np
a=np.linspace(1,2,5)#linspace (start,end,total_value) gives total number in range in equal distance
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [4]:
import numpy as np
np.random.seed(122)
matrix=np.random.randint(1,21,9).reshape(3,3)
matrix

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [5]:
np.sum(matrix)

116

In [6]:
np.min(matrix)

3

In [7]:
np.max(matrix)

17

In [8]:
np.max(matrix,axis=1)#finds row wise max


array([16, 17, 16])

In [9]:
np.max(matrix,axis=0)#finds coloumn wise max

array([17, 16, 16])

In [10]:
np.min(matrix,axis=0)#finds coloumn wise min

array([ 3, 11, 11])

In [12]:
np.min(matrix,axis=1)#finds row wise min

array([11, 13,  3])

In [13]:
np.cumsum(matrix)

array([ 16,  27,  40,  57,  70,  86,  89, 105, 116], dtype=int32)

In [16]:
import numpy as np
np.random.seed(122)
arr=np.random.randint(1,21,10)
np.random.shuffle(arr)
arr

array([13, 16, 16, 11, 16, 10, 11, 13, 17,  3])

In [18]:
np.unique(arr)


array([ 3, 10, 11, 13, 16, 17])

In [19]:
np.unique(arr).size

6

In [20]:
import numpy as np
arr=np.array([10,20,30,40,50,10,20])
np.unique(arr,return_index=True,return_counts=True)


(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 3, 4], dtype=int64),
 array([2, 2, 1, 1, 1], dtype=int64))

In [22]:
import  numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
import numpy as np
np.random.seed(122)
a=np.random.randint(1,21,9).reshape(3,3)
b=np.random.randint(50,85,9).reshape(3,3)


array([[71, 81, 56],
       [64, 81, 69],
       [63, 82, 70]])

In [26]:
a

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [27]:
b

array([[71, 81, 56],
       [64, 81, 69],
       [63, 82, 70]])

In [28]:
np.hstack((a,b))

array([[16, 11, 13, 71, 81, 56],
       [17, 13, 16, 64, 81, 69],
       [ 3, 16, 11, 63, 82, 70]])

In [29]:
np.vstack((a,b))

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11],
       [71, 81, 56],
       [64, 81, 69],
       [63, 82, 70]])

In [30]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [36]:
arr[1,0]

6

In [41]:
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
np_mat * 2
np_mat + np.array([10, 10])
np_mat+np_mat

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])