In [12]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
myarr=np.array(a)
print("a=",myarr)
print("Dimensions of the array =",myarr.ndim)

a= [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensions of the array = 2
Shape of the array =  (3, 3)


In [1]:
import numpy as np
arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [3]:
import numpy as np
arr=np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
import numpy as np
arr=np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [5]:
import numpy as np
arr=np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
import numpy as np
arr=np.eye(3)#square matrix(diagonal 1 and remaining zeros
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
import numpy as np
arr=np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [10]:
import numpy as np
arr=np.diag([2,3,4,5])#two dimensional array with  diagonal value
arr

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [11]:
import numpy as np
arr=np.diag([2,3,4,5])
np.diag(arr)#returns diagonal elements

array([2, 3, 4, 5])

In [14]:
import numpy as np
arr=np.random.randint(1,10,3)#randint gernerates random No. between in range syntax randint(min,max,total_values)
arr

array([2, 6, 8])

In [15]:
import numpy as np
arr=np.random.rand(5)#rand gernerates random No. between 0 to 1  syntax rand(total_values)
arr

array([0.18924337, 0.46974792, 0.84074143, 0.60366269, 0.90181465])

In [16]:
import numpy as np
arr=np.random.rand(2,3)#rand gernerates random No. between 0 to 1  for 2D rand(row,coloumn)
arr

array([[0.70391355, 0.72739843, 0.83863782],
       [0.46102787, 0.38211575, 0.67449343]])

In [17]:
import numpy as np
arr=np.random.randn(5)#randn gernerates random Number nearly zero(maybe positive or negative)  syntax randn(total_values)
arr

array([-1.88677123, -0.41277897, -0.62679365,  0.75187576, -0.41617658])

In [21]:
import numpy as np
a=[]
n=int(input("Enter size of list ="))
for i in range(n):
    val=int(input())
    a.append(val)

arr=np.array(a)
for  i in range(arr.size):
       print(arr[i])
sum=0
for i in range(arr.size):
    sum=sum+arr[i]
print(sum)
arr1=arr[2:5]#slicing syntx name[start:end:step] step nah dile by default 1 hobe
print(arr1)

Enter size of list =5
1
2
3
4
5
1
2
3
4
5
15
[3 4 5]


In [7]:
import numpy as np
arr=np.random.randint(1,100,12)
print(arr.shape)
arr=arr.reshape(6,2)#one dimensional to two dimensionsal
arr
arr=arr.reshape(12)#two dimensional to one dimensional
arr



(12,)


array([41, 35, 94, 66, 81, 76, 68, 26, 71, 16, 34, 46])

In [15]:
import numpy as np
np.random.seed(12)#seed function fixed the random numbers
arr=np.random.randint(1,100,10)
arr

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])

In [6]:
import numpy as np
row=int(input())
col=int(input())
matrix=[]
for i in range(row):
    a=[]
    for j in range(col):
        val=int(input())
        a.append(val)
    matrix.append(a)
arr=np.array(matrix)
for i in range(row)
    for j in range(col):
        print(arr[i,j],end=" ")
    print()


ValueError: invalid literal for int() with base 10: ''

In [8]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(a)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr[:2,1:3]#sliccing syntax array_name[row range,coloumn range]

array([[2, 3],
       [5, 6]])

In [15]:
import numpy as np
np.random.seed(111)
a=np.random.randint(1,500,30).reshape(5,6)
a

array([[341, 365, 469, 213,  87, 276],
       [170, 323, 119, 467, 297, 456],
       [442,   8, 269, 267, 450, 369],
       [217, 285, 271, 419,  22,  55],
       [201,  38, 461, 231, 187, 269]])

In [21]:
a[2:,3:]

array([[267, 450, 369],
       [419,  22,  55],
       [231, 187, 269]])

In [25]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [30]:
b=a[3:6]#slicing view vs copy concept.By default slicing is used view (using view if we change value in slicing ,it will change the value in main array)
b[:]=0
b
a

array([10, 20, 30,  0,  0,  0, 70, 80, 90])

In [33]:
import numpy as np
a=np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
b=a[3:6].copy()#No changes in main array
b[:]=0
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [7]:
import numpy as np
arr=np.arange(1,16)
arr>10
arr[arr%2==0]=100
arr

array([  1, 100,   3, 100,   5, 100,   7, 100,   9, 100,  11, 100,  13,
       100,  15])

In [27]:
import numpy as np
arr1=np.arange(1,5)
arr2=np.arange(5,9)
arr2

array([5, 6, 7, 8])

In [14]:
arr1

array([1, 2, 3, 4])

In [21]:
arr2

array([5, 6, 7, 8])

In [28]:
arr1+arr2

array([ 6,  8, 10, 12])

In [31]:
import numpy as np
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([5,6,7,8]).reshape(2,2)


array([[5, 6],
       [7, 8]])

In [32]:
a

array([[1, 2],
       [3, 4]])

In [33]:
b

array([[5, 6],
       [7, 8]])

In [36]:
a+b

array([[ 6,  8],
       [10, 12]])

In [37]:
a-b

array([[-4, -4],
       [-4, -4]])

In [38]:
a**b

array([[    1,    64],
       [ 2187, 65536]], dtype=int32)

In [39]:
a*b

array([[ 5, 12],
       [21, 32]])

In [40]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [42]:
a.dot(b)#matrix multiplication way

array([[19, 22],
       [43, 50]])